<a href="https://colab.research.google.com/github/alsantosad/SENAC_RESILIA_ANALISE_DE_DADOS/blob/main/M4_Projeto_Individual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##***PANDAS***

###**Importando Pandas**
```python
import pandas as pd:
```
Importa a biblioteca pandas e a apelida de pd. O pandas é uma biblioteca poderosa para manipulação e análise de dados em Python.



In [ ]:
import pandas as pd

###**Series em Pandas**
pd.Series

```Python
pd.Series(...):
```

Converte a lista em uma Série do pandas. Uma Série é uma estrutura de dados unidimensional que pode armazenar qualquer tipo de dado. Cada elemento na Série possui um rótulo, chamado de índice.

```Python
list('abcdef'):
```
Cria uma lista contendo os caracteres 'a', 'b', 'c', 'd', 'e' e 'f'. A função list() converte a string em uma lista de caracteres.

Veja:

```python
s1 = pd.Series(list('abcdef'))
s1
```

####***Exemplo Serie 1:***
Montando uma Series com lista.


A Série s1 foi criada com os valores 'a', 'b', 'c', 'd', 'e' e 'f', e os índices são automaticamente atribuídos de 0 a 5.

In [ ]:
s1 = pd.Series(list('abcdef'))
s1

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object

In [ ]:
# Criando um Dataframe com a pd.Series e mudando o valor de index de cada linha.
df = pd.DataFrame({'col1': s1.values}, index=['letra1', 'letra2', 'letra3', 'letra4', 'letra5', 'letra6'])
df

col1
letra1    a
letra2    b
letra3    c
letra4    d
letra5    e
letra6    f

####***Exemplo Serie 2:***

`pd.Series([...]):` Cria uma Série no pandas.

`[2, 4, 6, 8]:` Os valores que serão armazenados na Série.

 A Série s2 terá automaticamente índices atribuídos de 0 a 3, e você pode realizar diversas operações e análises de dados utilizando os recursos oferecidos pelo pandas para manipulação de Séries e DataFrames.

In [ ]:
s2 = pd.Series([2,4,6,8])
s2

0    2
1    4
2    6
3    8
dtype: int64

####***Exemplo Serie 3:***

`pd.Series([...], index=['a', 'b', 'c', 'd']):`

Cria uma Série no pandas com valores específicos e índices associados.

A principal diferença em relação à Série anterior (s2) é que, desta vez, os índices são especificados manualmente como `['a', 'b', 'c', 'd']`, em vez de serem gerados automaticamente. Isso permite associar rótulos personalizados aos elementos da Série, facilitando a referência aos valores por meio desses rótulos.

In [ ]:
# Nas Series, primeiro passamos os valores e depois o index.
s3 = pd.Series([2,4,6,8], index = ['a','b','c','d'])
s3

# Na Criação do DataFrame como as Series, entre chaves passamos o nome da coluna e depois a variaves da Series.
df = pd.DataFrame({'letras': s3})
df

letras
a       2
b       4
c       6
d       8

####***Exemplo Serie 3.1:***

`s3['b']`: Acessa o valor na Série s3 correspondente ao índice 'b'.

Neste caso específico, a Série s3 foi criada com índices personalizados, onde 'b' é um desses índices. Portanto, a expressão `s3['b']` retornará o valor associado ao índice 'b', que é 4. Esse tipo de indexação baseada em rótulos é uma característica poderosa das estruturas de dados do pandas.

In [ ]:
s3['b']

4

####***Exemplo Serie 3.2:***



`s3[['b', 'c']]`: Seleciona os valores da Série s3 correspondentes aos índices 'b' e 'c', resultando em uma nova Série.

A expressão retorna uma Série contendo os valores 4 e 6, que estão associados aos índices 'b' e 'c', respectivamente. O uso de uma lista `['b', 'c']` na indexação permite selecionar múltiplos valores ao mesmo tempo. Essa é uma funcionalidade flexível do pandas que facilita a manipulação de dados em conjuntos.

In [ ]:
s3[['b','c']]

b    4
c    6
dtype: int64

####***Exemplo Serie 4:***
Aqui utilizamos a função range() para os valores, com a função list() para os index.

O código `s4 = pd.Series(range(10), index=list('ababcedded'))` cria uma Série no pandas chamada s4 com valores de 0 a 9 e índices associados às letras 'a', 'b', 'a', 'b', 'c', 'e', 'd', 'd', 'e' e 'd'.

Em resumo:
`pd.Series(range(10), index=list('ababcedded'))`: Cria uma Série no pandas com valores de 0 a 9 e índices específicos.

Os índices são baseados na lista de caracteres 'ababcedded'. Cada letra na lista é associada a um valor na Série. Por exemplo, 'a' está associado a 0, 'b' está associado a 1, 'c' está associado a 4, e assim por diante.

In [ ]:
#
s4 = pd.Series(range(10), index = list('ababcedded'))
s4

a    0
b    1
a    2
b    3
c    4
e    5
d    6
d    7
e    8
d    9
dtype: int64

####***Exemplo Serie 4.0:***

A expressão s4['a'] realiza uma operação de indexação na Série s4, retornando uma nova Série que contém os valores associados ao índice 'a'. Em resumo:

`s4['a']`: Seleciona os valores da Série s4 associados ao índice 'a'.

Se a Série s4 for definida como no exemplo anterior, onde os índices 'a' estão associados aos valores 0 e 2, então `s4['a']` resultará em uma Série contendo esses valores.

Esta Série resultante mostra os valores 0 e 2 associados aos índices 'a'. Note que, como os índices não são únicos, a operação de indexação pode retornar múltiplos valores.

In [ ]:
s4['a']

a    0
a    2
dtype: int64

####***Exemplo Serie 4.1:***

s4['d']: Seleciona os valores da Série s4 associados ao índice 'd', resultando em uma nova Série.

[0]: Seleciona o primeiro elemento dessa nova Série.

Assumindo que a Série s4 tenha sido definida conforme mencionado anteriormente, onde os índices 'd' estão associados aos valores 6, 7 e 9, então s4['d'][0] resultará em:

In [ ]:
s4['d'][1]

7

In [ ]:
# Imprime a Serie 4
s4

a    0
b    1
a    2
b    3
c    4
e    5
d    6
d    7
e    8
d    9
dtype: int64

####***Exemplo Serie 4.2:***


A expressão `s4[s4 < 2]` realiza uma operação de filtragem na Série s4, retornando uma nova Série contendo apenas os elementos cujos valores são menores que 2. Em resumo:

`s4 < 2`: Cria uma Série de valores booleanos indicando se cada elemento na Série s4 é menor que 2.

`s4[s4 < 2]`: Seleciona apenas os elementos da Série s4 onde a condição é verdadeira, ou seja, onde o valor é menor que 2.

Assumindo que a Série s4 tenha sido definida conforme mencionado anteriormente, onde os primeiros três valores são associados aos índices 'a', 'b' e 'a', e assim por diante, então `s4[s4 < 2]` resultará em:

In [ ]:
s4[s4<2]

a    0
b    1
dtype: int64

In [ ]:
s4[s4>3]

c    4
e    5
d    6
d    7
e    8
d    9
dtype: int64

####***Exemplo Serie 4.3:***



In [ ]:
s4>3

a    False
b    False
a    False
b    False
c     True
e     True
d     True
d     True
e     True
d     True
dtype: bool

In [ ]:
s4+2

a     2
b     3
a     4
b     5
c     6
e     7
d     8
d     9
e    10
d    11
dtype: int64

In [ ]:
s4*2

a     0
b     2
a     4
b     6
c     8
e    10
d    12
d    14
e    16
d    18
dtype: int64

In [ ]:
dicio = {'a':100, 'b':200, 'c':300}
s5 = pd.Series(dicio)
s5

a    100
b    200
c    300
dtype: int64

In [ ]:
dicio2 = {'nome':'Maria', 'idade':'50','sexo':'feminino'}
s6 = pd.Series(dicio2)
s6

nome        Maria
idade          50
sexo     feminino
dtype: object

In [ ]:
dicionario = {'b': 100, 'c': 150, 'd': 200}
s = pd.Series(dicionario)
s

b    100
c    150
d    200
dtype: int64

In [ ]:
s = pd.Series(dicionario, list('abcd'))
s

a      NaN
b    100.0
c    150.0
d    200.0
dtype: float64

In [ ]:
s6 = pd.Series([1,2,3], index = ['c','b','a'])
s6

c    1
b    2
a    3
dtype: int64

In [ ]:
s*s6

a      NaN
b    200.0
c    150.0
d      NaN
dtype: float64

### ***NUMPY - ARRAYS***

In [ ]:
import numpy as np

In [ ]:
lista= list(range(1,10))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
array1 = np.array(lista)
array1

In [ ]:
type(array1)

In [ ]:
array1.dtype

In [ ]:
array1[1]

In [ ]:
array2 = np.array([(1,2,3),(4,5,6)])
array2

In [ ]:
array2.shape

In [ ]:
array2.dtype

In [ ]:
array3 = np.array([(1.5,2,3),(4.6,5,6)])
array3

In [ ]:
array4 = np.zeros((2,3))
array4

In [ ]:
array5 = np.ones((2,3))
array5

In [ ]:
array6 = np.arange(10,30,5)
array6

In [ ]:
array7 = np.random.rand(2,3)
array7

In [ ]:
array8 = np.array([(1,2,3),(4,5,6),(7,8,9)])
array8

In [ ]:
array8[:2]

In [ ]:
# 1.
array_numpy = np.array([10, 20, 30, 40, 50, 60, 70])
print(array_numpy)
print("Tipo dos elementos antes da subtração:", array_numpy.dtype)

# 2.
print(f"\n-> Realizamos a subtração de 5 em cada elemento:")
array_numpy -= 5
print(array_numpy)
print("Tipo dos elementos depois da subtração:", array_numpy.dtype)

# 3.
serie_pandas = pd.Series(array_numpy)
print(f"\n-> series do pandas:")
print(serie_pandas)

# 4.
print("\n-> Estatísticas da série:")

count1 = serie_pandas.count()
print("Quantidade de itens:", count1)

mean1 = serie_pandas.mean()
print("Média:", mean1)

min1 = serie_pandas.min()
print("Mínimo:", min1)

max1 = serie_pandas.max()
print("Máximo:", max1)

In [ ]:
array_numpy = np.array([10,20,30,40,50,60,70])
array_numpy

array_numpy = array_numpy - 5
array_numpy

array_pandas = pd.Series(array_numpy)
array_pandas

In [ ]:
# ATIVIDADE

# 1 questao
array_atividade = np.array((list(range(10,71, 10))))
print('1 questao\n',array_atividade,'\n')

# 2 questao
print('2 questao\n',array_atividade - 5,'\n')

# 3 questao
print('3 questao\n',pd.Series(array_atividade),'\n')

In [ ]:
#ATIVIDADE

lista = [10,20,30,40,50,60,70]
at=np.array(lista)

at

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
at - 5

array([ 5, 15, 25, 35, 45, 55, 65])

In [ ]:
at

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
at = at - 5
at

array([ 5, 15, 25, 35, 45, 55, 65])

###***Slice***

In [ ]:
array8[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2.reshape((3,2))

array([[1.2, 2. ],
       [3. , 4.6],
       [5. , 6. ]])

In [ ]:
narray = np.split(array8,3)
narray

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
arrayj = np.concatenate(narray)
arrayj

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2

array([[1.2, 2. , 3. ],
       [4.6, 5. , 6. ]])

In [ ]:
array2.max()

6.0

In [ ]:
array2.min()

1.2

In [ ]:
array2.sum()

21.8

In [ ]:
array2.mean()

3.6333333333333333

In [ ]:
import pandas as pd

In [ ]:
vingadores = ["thor","hulk","iron man","black panther", "captain USA"]
vingadores

['thor', 'hulk', 'iron man', 'black panther', 'captain USA']

In [ ]:
type(vingadores)

list

In [ ]:
serie_vingadores = pd.Series(vingadores)
serie_vingadores

0             thor
1             hulk
2         iron man
3    black panther
4      captain USA
dtype: object

In [ ]:
type(serie_vingadores)

pandas.core.series.Series

In [ ]:
array_vingadores = np.array(vingadores)
array_vingadores

array(['thor', 'hulk', 'iron man', 'black panther', 'captain USA'],
      dtype='<U13')

In [ ]:
array_serie = serie_vingadores.to_numpy()
array_serie

array(['thor', 'hulk', 'iron man', 'black panther', 'captain USA'],
      dtype=object)

### ***ATIVIDADE:SÉRIES***

####PRIMEIRA SÉRIE

**O QUE FAZER?**
1. Criar duas series pandas com 4 posições cada, realizar as quatro operações matemáticas
básicas entre as series e mostrar o resultado;
2. Criar uma terceira serie pandas com apenas 3 posições, realizar as quatro operações
matemáticas básicas com uma das series do exercício anterior e explicar o resultado.
➔ **COMO FAZER?**

Em grupos de 3 a 4 pessoas.
➔ **FECHAMENTO**
Compartilhar as impressões gerais da atividade e dúvidas.


In [ ]:
import pandas as pd

In [ ]:
Sa = pd.Series([3,6,9,12])
Sa

In [ ]:
Sb = pd.Series([5,10,15,20])
Sb

In [ ]:
Sa+Sb

In [ ]:
Sa*Sb

In [ ]:
Sa-Sb

In [ ]:
Sa/Sb

In [ ]:
Sc = pd.Series([1,2,3])
Sc

In [ ]:
Sc+Sa

In [ ]:
Sc-Sb

In [ ]:
Sc*Sa

In [ ]:
Sc/Sb

#### ATIVIDADE 2

cfriar séries para guardar as seguintes informações sobre notas de alunos.
aluna maria tirou 7 no teste 10 na prova
aluno bruno tirou 6 no teste 8 na prova
aluno Lucas tirou 6 no teste e 10 na prova

In [ ]:
# prompt: criar séries para guardar as seguintes informações sobre notas de alunos. aluna maria tirou 7 no teste 10 na prova aluno bruno tirou 6 no teste 8 na prova aluno Lucas tirou 6 no teste e 10 na prova

notas = pd.Series({'Maria': [7, 10], 'Bruno': [6, 8], 'Lucas': [6, 10]})
notas

Atividade: Fusão
➔ O QUE FAZER?
Escrever um código.
➔ COMO FAZER?
1. Crie um array numpy com os números [10 20 30 40 50 60 70];
2. Subtraia 5 de todos os números do array e reatribua no array original. Veja o tipo dos elementos
no array antes e depois dessa operação;
3. Converta o array para uma series do pandas;

In [ ]:
array_numpy = np.array([10,20,30,40,50,60,70])
array_numpy

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
array_numpy = array_numpy - 5
array_numpy

array([ 5, 15, 25, 35, 45, 55, 65])

In [ ]:
array_pandas = pd.Series(array_numpy)
array_pandas

0     5
1    15
2    25
3    35
4    45
5    55
6    65
dtype: int32

In [ ]:
array_pandas.max()

65

In [ ]:
array_pandas.min()

5

In [ ]:
array_pandas.sum()

245

In [ ]:
array_pandas.mean()

35.0

### **MATRIZES**

In [ ]:
import pandas as pd
import numpy as np

###***Criando um DataFrame com pd.Series***

In [ ]:
s1 = pd.Series(list('abcdef'))
s1

In [ ]:
df = pd.DataFrame({'col1': s1.values}, index=['letra1', 'letra2', 'letra3', 'letra4', 'letra5', 'letra6'])
df

In [ ]:
s3 = pd.Series([2,4,6,8], index = ['a','b','c','d'])
s3

df = pd.DataFrame({'uau': s3})
df

###***Criando um Array bidimensional com Numpy***

In [ ]:
array1 = np.array ([[0,1,2],[3,4,5]])
array1

array([[0, 1, 2],
       [3, 4, 5]])

1. Cria um array bidimensional: Usa NumPy para criar o array array1 com números.

2. Converte o array em DataFrame: Utiliza pandas para transformar o array em um DataFrame chamado dataframe1 com colunas nomeadas ('col1', 'col2', 'col3').

3. Visualiza o DataFrame: Ao exibir dataframe1, você mostrará uma tabela organizada dos dados.

In [ ]:
dataframe1 = pd.DataFrame(array1, columns=['col1','col2','col3'])
dataframe1

col1  col2  col3
0     0     1     2
1     3     4     5

### ***CRIANDO E MANIPULANDO UM DATA FRAME***

Criação de Dados: É criado um dicionário chamado pop_data com chaves representando times de futebol (Flamengo, Palmeiras, Corinthians) e valores sendo listas de pontuações ao longo dos anos.

Conversão para DataFrame: Utiliza-se o pandas para transformar o dicionário em um DataFrame chamado futebol. Cada time representa uma coluna e as pontuações ao longo dos anos são organizadas em linhas.

Definição de Índice: O parâmetro index é usado para definir os anos (2017 a 2021) como índices das linhas do DataFrame.

Visualização do DataFrame: Ao exibir futebol, você terá uma tabela que mostra as pontuações dos times de futebol ao longo dos anos.

In [ ]:
#
pop_data = {'Flamengo': [56,72,90,71, 71],
            'Palmeiras': [63,80,74,58,66],
            'Corinthias': [72,44,56,51,57]}

futebol = pd.DataFrame(pop_data, index=[2017,2018,2019,2020,2021])
futebol

Flamengo  Palmeiras  Corinthias
2017        56         63          72
2018        72         80          44
2019        90         74          56
2020        71         58          51
2021        71         66          57

In [ ]:
#Retornando os dados como Series
futebol['Flamengo']

2017    56
2018    72
2019    90
2020    71
2021    71
Name: Flamengo, dtype: int64

In [ ]:
#Retornando somente os Valores
futebol.values

array([[56, 63, 72],
       [72, 80, 44],
       [90, 74, 56],
       [71, 58, 51],
       [71, 66, 57]])

In [ ]:
#Retornando somente os Valores da Coluna |'Flamengo'|
#Atributo do DataFrame |.values|
futebol['Flamengo'].values

array([56, 72, 90, 71, 71])

In [ ]:
#Contagem de cada Valor da coluna |'Flamengo'|
futebol['Flamengo'].value_counts()

71    2
56    1
72    1
90    1
Name: Flamengo, dtype: int64

In [ ]:
#Criando uma nova coluna
#Aplicando valores nulos com a função |np.NaN|
futebol['nova'] = np.NaN
futebol

Flamengo  Palmeiras  Corinthias  nova
2017        56         63          72   NaN
2018        72         80          44   NaN
2019        90         74          56   NaN
2020        71         58          51   NaN
2021        71         66          57   NaN

Transposição: A letra "T" indica a transposição, que basicamente troca as linhas pelas colunas e vice-versa no DataFrame.

Impacto na Tabela: Se as colunas originalmente representavam times e as linhas representavam anos, após a transposição, as colunas passarão a representar anos e as linhas representarão times.

Facilita a Visualização: Pode ser útil quando você deseja analisar ou apresentar os dados de uma maneira diferente, trocando a perspectiva de linhas para colunas.

Portanto, futebol.T fornece uma visão transposta do DataFrame original, simplificando a interpretação dos dados a partir de uma perspectiva diferente.

In [ ]:
#|T| função de transposição
futebol.T

2017  2018  2019  2020  2021
Flamengo    56.0  72.0  90.0  71.0  71.0
Palmeiras   63.0  80.0  74.0  58.0  66.0
Corinthias  72.0  44.0  56.0  51.0  57.0
nova         NaN   NaN   NaN   NaN   NaN

In [ ]:
#Renomeando uma coluna sem alterar o dataframe
futebol.rename(columns={'nova':'Atlético'})

Flamengo  Palmeiras  Corinthias  Atlético
2017        56         63          72       NaN
2018        72         80          44       NaN
2019        90         74          56       NaN
2020        71         58          51       NaN
2021        71         66          57       NaN

In [ ]:
#Alterando o nome da Coluna no DataFrame
futebol = futebol.rename(columns = {'nova' : 'Atlético'})
futebol

Flamengo  Palmeiras  Corinthias  Atlético
2017        56         63          72       NaN
2018        72         80          44       NaN
2019        90         74          56       NaN
2020        71         58          51       NaN
2021        71         66          57       NaN

In [ ]:
#Alterando o nome da coluna com a função |, inplace=True|
futebol.rename(columns = {'Atlético':'CAM'}, inplace=True)
futebol

Flamengo  Palmeiras  Corinthias  CAM
2017        56         63          72  NaN
2018        72         80          44  NaN
2019        90         74          56  NaN
2020        71         58          51  NaN
2021        71         66          57  NaN

In [ ]:
#Criando uma nova coluna chamada |'Flamengo2'| com a multiplicação dos valores
#da coluna Flamengo.
futebol['Flamengo2'] = futebol['Flamengo']*2
futebol

Flamengo  Palmeiras  Corinthias  CAM  Flamengo2
2017        56         63          72  NaN        112
2018        72         80          44  NaN        144
2019        90         74          56  NaN        180
2020        71         58          51  NaN        142
2021        71         66          57  NaN        142


A função `futebol.describe()` fornece estatísticas descritivas do DataFrame futebol. Aqui está uma explicação simplificada:

Resumo Estatístico: Gera um resumo estatístico que inclui diversas métricas descritivas para cada coluna do DataFrame.

As métricas incluídas no resumo são:

Contagem (count): Número de elementos não nulos.
Média (mean): Média aritmética dos valores.
Desvio padrão (std): Medida de dispersão dos valores.
Valor mínimo (min): Menor valor na coluna.
Quartis (25%, 50%, 75%): Valores que dividem os dados em quartis.
Valor máximo (max): Maior valor na coluna.
Ajuda na Análise Rápida: Facilita uma rápida compreensão da distribuição e variação dos dados em cada coluna.

Portanto, futebol.describe() é uma ferramenta útil para ter uma visão estatística resumida dos dados do DataFrame.

In [ ]:
futebol.describe()

Flamengo  Palmeiras  Corinthias  CAM   Flamengo2
count   5.000000   5.000000    5.000000  0.0    5.000000
mean   72.000000  68.200000   56.000000  NaN  144.000000
std    12.062338   8.786353   10.319884  NaN   24.124676
min    56.000000  58.000000   44.000000  NaN  112.000000
25%    71.000000  63.000000   51.000000  NaN  142.000000
50%    71.000000  66.000000   56.000000  NaN  142.000000
75%    72.000000  74.000000   57.000000  NaN  144.000000
max    90.000000  80.000000   72.000000  NaN  180.000000

In [ ]:
futebol.rename(columns = {'CAM':'Atlético'}, inplace=True)
futebol

Flamengo  Palmeiras  Corinthias  Atlético  Flamengo2
2017        56         63          72       NaN        112
2018        72         80          44       NaN        144
2019        90         74          56       NaN        180
2020        71         58          51       NaN        142
2021        71         66          57       NaN        142

In [ ]:
#Soma todos os valores das colunas linha por linha
futebol.sum()

Flamengo      360.0
Palmeiras     341.0
Corinthias    280.0
Atlético        0.0
Flamengo2     720.0
dtype: float64

In [ ]:
futebol

Flamengo  Palmeiras  Corinthias  Atlético  Flamengo2
2017        56         63          72       NaN        112
2018        72         80          44       NaN        144
2019        90         74          56       NaN        180
2020        71         58          51       NaN        142
2021        71         66          57       NaN        142

In [ ]:
#Somou o valor da coluna, coluna por coluna
futebol.sum(axis='columns')

2017    303.0
2018    340.0
2019    400.0
2020    322.0
2021    336.0
dtype: float64

###***Função Mediana***
> dataframe.median(), dataframe.mean()


A função futebol.median() retorna as medianas de cada coluna no DataFrame futebol. De forma resumida:

Mediana: A mediana é o valor que divide os dados ordenados ao meio. Em um conjunto de dados, metade dos valores estão abaixo da mediana e metade acima.

Aplicação em Colunas: A função calcula a mediana para cada coluna do DataFrame, fornecendo uma medida de tendência central para cada série de dados.

Útil para Tendência Central: Ajuda a entender o valor central típico de cada time ao longo dos anos em relação às pontuações, ignorando extremos.

Portanto, futebol.median() é útil para analisar a tendência central das pontuações de cada time no conjunto de dados.

In [ ]:
futebol.median()

Flamengo       71.0
Palmeiras      66.0
Corinthias     56.0
Atlético        NaN
Flamengo2     142.0
dtype: float64

In [ ]:
# max: Retorna o valor máximo ao longo de um eixo (geralmente colunas ou linhas) em um DataFrame ou Series.
futebol.max()

Flamengo       90.0
Palmeiras      80.0
Corinthias     72.0
Atlético        NaN
Flamengo2     180.0
dtype: float64

In [ ]:
# min: Retorna o valor mínimo ao longo de um eixo em um DataFrame ou Series.
futebol.min()

Flamengo       56.0
Palmeiras      58.0
Corinthias     44.0
Atlético        NaN
Flamengo2     112.0
dtype: float64

In [ ]:
# median: Retorna a mediana ao longo de um eixo em um DataFrame ou Series.
futebol.isnull()

Flamengo  Palmeiras  Corinthias  Atlético  Flamengo2
2017     False      False       False      True      False
2018     False      False       False      True      False
2019     False      False       False      True      False
2020     False      False       False      True      False
2021     False      False       False      True      False

####***ATIVIDADE***
> Criação do Dataframe, Calculo da Média, Criação de uma nova tabela e exibição do Resultado.

Foi solicitada a criação de um DataFrame chamado nota com notas de três alunos (Ana, Antônio, Beatriz) em quatro disciplinas (Matemática, Física, Química, Biologia).
Cálculo da Média por Aluno:

Foi solicitado o cálculo da média das notas para cada aluno e a adição de uma coluna chamada 'Média' ao DataFrame.
Cálculo da Média Geral da Turma:

Foi solicitado o cálculo da média geral de todas as notas na tabela, incluindo as médias individuais dos alunos.
Exibição dos Resultados:

Foi solicitada a exibição da tabela com as médias das notas de cada aluno e a média geral da turma.

In [ ]:
# Importando as Bibliotecas
import pandas as pd
import numpy as np

#Criando uma estrutura de dados
notas_data = {'Matemática': [6, 5, 5],
              'Física': [4, 7, 6],
              'Química': [5, 5, 7],
              'Biologia': [8, 5, 4]}

#Criando um DataFrame das notas
nota = pd.DataFrame(notas_data, index=['Ana', 'Antônio', 'Beatriz'])

# Calcular a média ao longo das linhas (axis=1)
nota['Média'] = nota.mean(axis=1)

# Calcular a média geral de todas as notas na tabela
media_geral_turma = nota.values.mean()

# Exibir a nova tabela com as médias das notas, a média geral da turma e a média geral de todas as notas
print(nota)
print("\nMédia Geral da Turma:", media_geral_turma)

#### ***ATIVIDADE 1***
> Criar um DataFrame com duas linhas e duas colunas de valores inteiros; (1,2,3,4) colunas 1 e coluna 2 como rótulo de coluna

> Depois de criado, atualizar os valores da primeira coluna multiplicando os valores existentes por 2”;

> Criar uma nova coluna com todos os valores nulos.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dados = {'Coluna 1':[1,2],
         'Coluna 2': [3,4]}
dados

{'Coluna 1': [1, 2], 'Coluna 2': [3, 4]}

In [ ]:
df = pd.DataFrame(dados)
df

In [ ]:
df['Coluna 1']*2


In [ ]:
arrayatv = np.array([[1, 2], [3, 4]])
arrayatv

In [ ]:
dfatv = pd.DataFrame (arrayatv, columns=['col1', 'col2'])
dfatv

#### ***ATIVIDADE 1.2***
> Criando um Dataframe com Arrays,
multiplicando valores, criando uma nova coluna com valores nulos.

> Criar um DataFrame com duas linhas e duas colunas de valores inteiros; (1,2,3,4) colunas 1 e coluna 2 como rótulo de coluna

> Depois de criado, atualizar os valores da primeira coluna multiplicando os valores existentes por 2”;

> Criar uma nova coluna com todos os valores nulos.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dados = np.array([[1, 2], [3, 4]])

In [ ]:
# Crie um dataframe com 2 colunas de dados com array

df = pd.DataFrame(dados, columns=['col1', 'col2'])
df

col1  col2
0     1     2
1     3     4

In [ ]:
df['col1']*2

0    2
1    6
Name: col1, dtype: int64

In [ ]:
df['nova'] = np.NaN
df

col1  col2  nova
0     1     2   NaN
1     3     4   NaN

###***Como fatiar um Banco de Dados***

In [ ]:
import pandas as pd
import numpy as np

#Lendo Csv pelo link do site
url = 'https://raw.githubusercontent.com/parvathy-nsarma/Walmart-Data/main/Walmart_Store_sales.csv'
walmart = pd.read_csv(url)
walmart

Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572   
1         1  12-02-2010    1641957.44             1        38.51       2.548   
2         1  19-02-2010    1611968.17             0        39.93       2.514   
3         1  26-02-2010    1409727.59             0        46.63       2.561   
4         1  05-03-2010    1554806.68             0        46.50       2.625   
...     ...         ...           ...           ...          ...         ...   
6430     45  28-09-2012     713173.95             0        64.88       3.997   
6431     45  05-10-2012     733455.07             0        64.89       3.985   
6432     45  12-10-2012     734464.36             0        54.47       4.000   
6433     45  19-10-2012     718125.53             0        56.47       3.969   
6434     45  26-10-2012     760281.43             0        58.85       3.882   

             CPI  Unemployment  
0     211.096358         8.106  
1     211.242170         8.106  
2     211.289143         8.106  
3     211.319643         8.106  
4     211.350143         8.106  
...          ...           ...  
6430  192.013558         8.684  
6431  192.170412         8.667  
6432  192.327265         8.667  
6433  192.330854         8.667  
6434  192.308899         8.667  

[6435 rows x 8 columns]

***Fatiando com Slice***

A expressão walmart[:10]['Weekly_Sales'] extrai as vendas semanais das primeiras 10 linhas do DataFrame 'walmart'. Em resumo, ela fornece um subset das informações de vendas para as 10 primeiras entradas do conjunto de dados.

In [ ]:
walmart[:10]['Weekly_Sales']

0    1643690.90
1    1641957.44
2    1611968.17
3    1409727.59
4    1554806.68
5    1439541.59
6    1472515.79
7    1404429.92
8    1594968.28
9    1545418.53
Name: Weekly_Sales, dtype: float64

***Função `.LOC`***

A expressão walmart.loc[0:10]['Date'] está sendo usada para selecionar as datas na coluna 'Date' do DataFrame 'walmart' para as linhas de 0 a 10, inclusive. Em resumo, ela extrai um subconjunto específico de datas do início ao décimo elemento do DataFrame.

In [ ]:
#Extraindo um dado Especifico
walmart.loc[0]['Date']
#Extraindo mais dados Especificos
walmart.loc[0:10]['Date']

A expressão walmart[:1]['Date'] extrai a data da primeira linha do DataFrame 'walmart'. Em resumo, essa expressão obtém informações específicas da primeira entrada na coluna 'Date'.

In [ ]:
walmart[:1]['Date']

0    05-02-2010
Name: Date, dtype: object

***Função `.ILOC`***

A expressão walmart.iloc[0,1] retorna o valor localizado na primeira linha e segunda coluna do DataFrame 'walmart'.

In [ ]:
walmart.iloc[0,1]

42.31

A expressão walmart2 = walmart.T realiza a transposição do DataFrame walmart, trocando suas linhas por colunas e vice-versa. Portanto, walmart2 será uma versão transposta do DataFrame original. Essa operação pode ser útil em certos casos para manipulação ou análise de dados, dependendo da orientação desejada para os dados.

In [ ]:
walmart2 = walmart.T
walmart2


A expressão walmart.loc[0] é usada para obter todas as informações da linha de índice 0 no DataFrame walmart. Ela retorna uma série contendo os valores associados a cada coluna para a primeira linha do DataFrame. Essa abordagem é útil quando você deseja acessar todas as informações de uma entrada específica no conjunto de dados.

In [ ]:
walmart.loc[0]

Store                    1
Date            05-02-2010
Weekly_Sales     1643690.9
Holiday_Flag             0
Temperature          42.31
Fuel_Price           2.572
CPI             211.096358
Unemployment         8.106
Name: 0, dtype: object


A expressão walmart.loc[[1,2]] é usada para obter todas as informações das linhas de índices 1 e 2 no DataFrame walmart. Ela retorna um novo DataFrame contendo as informações associadas a esses índices. Essa abordagem é útil quando você deseja acessar dados específicos de várias entradas no conjunto de dados.

In [ ]:
walmart.loc[[1,2]]


A expressão walmart.loc[walmart['Holiday_Flag'] == 1] é usada para selecionar todas as linhas no DataFrame walmart onde a coluna 'Holiday_Flag' é igual a 1. Ela retorna um novo DataFrame contendo apenas as entradas em que a condição especificada é verdadeira. Essa abordagem é útil quando você deseja filtrar as informações com base em uma condição específica, neste caso, quando o valor da coluna 'Holiday_Flag' é 1.

In [ ]:
walmart.loc[walmart['Holiday_Flag'] == 1]

A expressão walmart.loc[walmart['Temperature'] > 90] é utilizada para selecionar todas as linhas no DataFrame walmart onde os valores na coluna 'Temperature' são maiores que 90. Isso cria um novo DataFrame que inclui apenas as entradas que atendem a essa condição específica. Essa abordagem é útil quando você deseja filtrar informações com base em critérios específicos, neste caso, quando a temperatura é superior a 90.

In [ ]:
walmart.loc[(walmart['Temperature'] > 90)]

A expressão walmart.loc[(walmart['Temperature'] > 90) & (walmart['Holiday_Flag'] == 1)] é usada para selecionar as linhas no DataFrame walmart que atendem a duas condições simultaneamente:

A temperatura (na coluna 'Temperature') é maior que 90.
O sinalizador de feriado (na coluna 'Holiday_Flag') é igual a 1.
O operador & representa a condição lógica "E" entre as duas condições. O resultado é um novo DataFrame contendo apenas as entradas que satisfazem ambas as condições. Essa abordagem é útil quando você deseja filtrar dados com base em múltiplos critérios simultaneamente.

In [ ]:
walmart.loc[(walmart['Temperature'] > 90) & (walmart['Holiday_Flag'] == 1)]

A expressão walmart.query('Holiday_Flag == 1') usa o método query do pandas para selecionar todas as linhas no DataFrame walmart onde o valor na coluna 'Holiday_Flag' é igual a 1. Essa abordagem oferece uma maneira mais concisa de realizar essa filtragem, sem a necessidade de usar o método loc e os operadores lógicos diretamente.

Essencialmente, a função query permite que você especifique uma expressão condicional de maneira mais legível e compacta. O resultado é um novo DataFrame contendo apenas as entradas que atendem à condição especificada.

In [ ]:
walmart.query('Holiday_Flag == 1')

A expressão walmart.query('39 <= Temperature > 50') procura no DataFrame walmart as linhas onde o valor na coluna 'Temperature' está entre 39 (inclusive) e 50 (exclusive). A correção sugerida para evitar comparações encadeadas é usar operadores lógicos separados.

In [ ]:
walmart.query('39 <= Temperature > 50')

A expressão walmart.query('Store in [1, 3]') está correta. Ela utiliza o método query do pandas para selecionar as linhas no DataFrame walmart onde o valor na coluna 'Store' está presente na lista [1, 3]. Isso resultará em um novo DataFrame contendo apenas as entradas correspondentes às lojas 1 e 3.

In [ ]:
walmart.query('Store in [1,3]')

A expressão walmart.query('Temperature > @tempe') utiliza o método query do pandas e a notação @ para referenciar variáveis externas. Neste caso, a variável tempe com valor 50.0 é usada na condição para selecionar as linhas no DataFrame walmart onde o valor na coluna 'Temperature' é maior que 50.0. Isso resulta em um novo DataFrame contendo apenas as entradas que atendem a essa condição específica de temperatura.

In [ ]:
tempe = 50.0
walmart.query('Temperature > @tempe')

### ***ATIVIDADE: Manipulando o Titanic - Part 1***

In [ ]:
import pandas as pd
import numpy as np

#Lendo Csv pelo link do site
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
titanic = pd.read_csv(url)
titanic

In [ ]:
#1. Imprimir da linha 2 até a linha 4 do DataFrame carregado;
titanic[2:5]

In [ ]:
#2. Imprimir as linhas que tiverem a coluna “Age” inferior a 30;
titanic.loc[titanic['Age'] <30]

In [ ]:
#3. Imprimir o valor da coluna “Pclass” igual a 3;
titanic.loc[titanic['Pclass'] == 3]

In [ ]:
#Extra: Imprimir as linhas que tiverem as colunas “survived” igual a 1 e “Pclass” inferior a 2
titanic.loc[(titanic['Survived'] == 1) & (titanic['Pclass'] < 2)]

###***Mais Operações***

A expressão walmart2 = walmart.copy() cria uma cópia independente do DataFrame original walmart e atribui essa cópia à variável walmart2. Essa abordagem é útil para evitar que as alterações feitas em walmart2 afetem o DataFrame original. Assim, walmart2 e walmart tornam-se dois DataFrames distintos, cada um com sua própria instância de dados.

In [ ]:
import pandas as pd
import numpy as np

#Lendo Csv pelo link do site
url = 'https://raw.githubusercontent.com/parvathy-nsarma/Walmart-Data/main/Walmart_Store_sales.csv'
walmart = pd.read_csv(url)
walmart

A expressão walmart2 = walmart.copy() cria uma cópia independente do DataFrame original walmart e atribui essa cópia à variável walmart2. Isso significa que walmart2 é uma versão separada do DataFrame original, permitindo a manipulação dos dados em walmart2 sem afetar o DataFrame original walmart.

In [ ]:
walmart2 = walmart.copy()
walmart2

A expressão del walmart2['CPI'] remove a coluna 'CPI' do DataFrame walmart2. Essa operação é feita no local, ou seja, ela modifica o DataFrame walmart2 diretamente. Após essa operação, o DataFrame walmart2 não conterá mais a coluna 'CPI'.

In [ ]:
del walmart2['CPI']
walmart2

Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572   
1         1  12-02-2010    1641957.44             1        38.51       2.548   
2         1  19-02-2010    1611968.17             0        39.93       2.514   
3         1  26-02-2010    1409727.59             0        46.63       2.561   
4         1  05-03-2010    1554806.68             0        46.50       2.625   
...     ...         ...           ...           ...          ...         ...   
6430     45  28-09-2012     713173.95             0        64.88       3.997   
6431     45  05-10-2012     733455.07             0        64.89       3.985   
6432     45  12-10-2012     734464.36             0        54.47       4.000   
6433     45  19-10-2012     718125.53             0        56.47       3.969   
6434     45  26-10-2012     760281.43             0        58.85       3.882   

      Unemployment  
0            8.106  
1            8.106  
2            8.106  
3            8.106  
4            8.106  
...            ...  
6430         8.684  
6431         8.667  
6432         8.667  
6433         8.667  
6434         8.667  

[6435 rows x 7 columns]


A expressão walmart2.drop(0) remove a linha com o índice 0 do DataFrame walmart2. Se desejar alterar o DataFrame original, você pode usar inplace=True. Caso contrário, pode atribuir o resultado a uma nova variável para manter uma cópia modificada.

In [ ]:
walmart2.drop(0)

Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
1         1  12-02-2010    1641957.44             1        38.51       2.548   
2         1  19-02-2010    1611968.17             0        39.93       2.514   
3         1  26-02-2010    1409727.59             0        46.63       2.561   
4         1  05-03-2010    1554806.68             0        46.50       2.625   
5         1  12-03-2010    1439541.59             0        57.79       2.667   
...     ...         ...           ...           ...          ...         ...   
6430     45  28-09-2012     713173.95             0        64.88       3.997   
6431     45  05-10-2012     733455.07             0        64.89       3.985   
6432     45  12-10-2012     734464.36             0        54.47       4.000   
6433     45  19-10-2012     718125.53             0        56.47       3.969   
6434     45  26-10-2012     760281.43             0        58.85       3.882   

      Unemployment  
1            8.106  
2            8.106  
3            8.106  
4            8.106  
5            8.106  
...            ...  
6430         8.684  
6431         8.667  
6432         8.667  
6433         8.667  
6434         8.667  

[6434 rows x 7 columns]

A expressão walmart2.drop([0,3], inplace=True) remove as linhas de índices 0 e 3 do DataFrame walmart2 e atualiza o DataFrame no local (devido ao argumento inplace=True). Isso significa que as alterações são aplicadas diretamente ao DataFrame walmart2, e não é necessário atribuir o resultado a uma nova variável.

In [ ]:
walmart2.drop([0,3], inplace= True)
walmart2

Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
1         1  12-02-2010    1641957.44             1        38.51       2.548   
2         1  19-02-2010    1611968.17             0        39.93       2.514   
4         1  05-03-2010    1554806.68             0        46.50       2.625   
5         1  12-03-2010    1439541.59             0        57.79       2.667   
6         1  19-03-2010    1472515.79             0        54.58       2.720   
...     ...         ...           ...           ...          ...         ...   
6430     45  28-09-2012     713173.95             0        64.88       3.997   
6431     45  05-10-2012     733455.07             0        64.89       3.985   
6432     45  12-10-2012     734464.36             0        54.47       4.000   
6433     45  19-10-2012     718125.53             0        56.47       3.969   
6434     45  26-10-2012     760281.43             0        58.85       3.882   

      Unemployment  
1            8.106  
2            8.106  
4            8.106  
5            8.106  
6            8.106  
...            ...  
6430         8.684  
6431         8.667  
6432         8.667  
6433         8.667  
6434         8.667  

[6433 rows x 7 columns]


A expressão walmart2.drop(['Holiday_Flag','Unemployment'], inplace=True, axis='columns') remove as colunas 'Holiday_Flag' e 'Unemployment' do DataFrame walmart2. A opção inplace=True indica que as alterações devem ser feitas diretamente no DataFrame walmart2, e axis='columns' especifica que as colunas (e não linhas) devem ser removidas. Após essa operação, o DataFrame walmart2 não conterá mais essas duas colunas.

In [ ]:
walmart2.drop(['Holiday_Flag','Unemployment'], inplace=True, axis='columns')
walmart2

Store        Date  Weekly_Sales  Temperature  Fuel_Price
1         1  12-02-2010    1641957.44        38.51       2.548
2         1  19-02-2010    1611968.17        39.93       2.514
4         1  05-03-2010    1554806.68        46.50       2.625
5         1  12-03-2010    1439541.59        57.79       2.667
6         1  19-03-2010    1472515.79        54.58       2.720
...     ...         ...           ...          ...         ...
6430     45  28-09-2012     713173.95        64.88       3.997
6431     45  05-10-2012     733455.07        64.89       3.985
6432     45  12-10-2012     734464.36        54.47       4.000
6433     45  19-10-2012     718125.53        56.47       3.969
6434     45  26-10-2012     760281.43        58.85       3.882

[6433 rows x 5 columns]

A expressão walmart2.index.name = 'Linhas' define o nome da coluna de índices do DataFrame walmart2 como 'Linhas', e walmart2.columns.name = 'Colunas' define o nome da linha de colunas como 'Colunas'. Essa atribuição de nomes é útil para fornecer rótulos descritivos aos índices e colunas do DataFrame. O DataFrame walmart2 agora terá esses rótulos associados aos índices e colunas, tornando mais fácil entender e referenciar essas partes do DataFrame.

In [ ]:
# Organizando melhor as linhas e Colunas
walmart2.index.name = 'Linhas'
walmart2.columns.name = 'Colunas'
walmart2

Colunas  Store        Date  Weekly_Sales  Temperature  Fuel_Price
Linhas                                                           
1            1  12-02-2010    1641957.44        38.51       2.548
2            1  19-02-2010    1611968.17        39.93       2.514
4            1  05-03-2010    1554806.68        46.50       2.625
5            1  12-03-2010    1439541.59        57.79       2.667
6            1  19-03-2010    1472515.79        54.58       2.720
...        ...         ...           ...          ...         ...
6430        45  28-09-2012     713173.95        64.88       3.997
6431        45  05-10-2012     733455.07        64.89       3.985
6432        45  12-10-2012     734464.36        54.47       4.000
6433        45  19-10-2012     718125.53        56.47       3.969
6434        45  26-10-2012     760281.43        58.85       3.882

[6433 rows x 5 columns]

A expressão obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c']) cria uma Series chamada obj com os valores [4.5, 7.2, -5.3, 3.6] e os índices correspondentes ['d', 'b', 'a', 'c']. Essa Series é basicamente uma estrutura unidimensional que associa valores a rótulos de índice.

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


A expressão obj2 = obj.reindex(['a','b','c','d','e','f']) reindexa a Series obj de acordo com a ordem especificada na lista fornecida. Isso significa que o índice da nova Series (obj2) seguirá a ordem ['a','b','c','d','e','f'].

Se algum índice em 'obj' não estiver presente na lista, o valor correspondente em 'obj2' será NaN (Not a Number), indicando um valor ausente.

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e','f'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
f    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(10))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
dtype: object

A expressão cria um DataFrame chamado frame com valores de 0 a 8, organizados em um formato 3x3. As linhas são rotuladas como 'a', 'c' e 'd', e as colunas como 'Ohio', 'Texas' e 'California'. Cada célula contém um valor específico.

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                        index=['a','c','d'],
                        columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

A expressão frame2 = frame.reindex(['a','b','c','d']) reindexa as linhas do DataFrame frame de acordo com a ordem especificada na lista ['a', 'b', 'c', 'd']. Se algum rótulo na lista não estiver presente nos índices originais do DataFrame, a linha correspondente em frame2 será preenchida com valores NaN.

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

A expressão frame3 = frame.reindex(columns=['Ohio', 'Texas', 'Miami', 'California']) reindexa as colunas do DataFrame frame de acordo com a ordem especificada na lista ['Ohio', 'Texas', 'Miami', 'California']. Se alguma coluna na lista não estiver presente nas colunas originais do DataFrame, a coluna correspondente em frame3 será adicionada com valores NaN.

In [ ]:
frame3 = frame.reindex(columns = ['Ohio', 'Texas', 'Miami', 'California'])
frame3

Ohio  Texas  Miami  California
a     0      1    NaN           2
c     3      4    NaN           5
d     6      7    NaN           8

In [ ]:
frame4 = frame.reindex(columns = ['Ohio', 'Miami', 'California'])
frame4

Ohio  Miami  California
a     0    NaN           2
c     3    NaN           5
d     6    NaN           8

In [ ]:
frame5 = frame.reindex(['a', 'b', 'c', 'd'], columns=['Texas', 'Utah', 'California'])
frame5

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## ***Importando CSV do Google Drive***

In [ ]:
import os
from google.colab import drive
import pandas as pd

# Montar o Google Drive
drive.mount ('/content/drive', force_remount=True)

#Caminho para o arquivo .csv no google drive
csv_path = '/content/drive/MyDrive/ANALISTA DE DADOS/PROJETOS SENAC ANALISTA DE DADOS/PROJETO EM GRUPO - MODULO 4/precos-semestrais-ca-2022-01.csv'

# Ler o arquivo .csv usando Pandas
df = pd.read_csv(csv_path, encoding='utf-8', sep=';')

display(df)

## ***Importando CSV do SAMPLE_DATA***

In [ ]:
import pandas as pd

csv_path = '/content/Preços semestrais - AUTOMOTIVOS_2023.01.1.csv'
df_csv = pd.read_csv(csv_path, encoding='utf-8', sep=';')

print('\nConteúdo do arquivo .csv:')
print(df_csv)

## ***Importando Banco de um LINK***

In [ ]:
import pandas as pd
import numpy as np

#Lendo Csv pelo link do site
url = 'https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv'
walmart = pd.read_csv(url)
walmart

##***LINKS E SITES IMPORTANTES***

In [ ]:
https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.html

#***PROJETO INDIVIDUAL M4***

##***CONTEXTO***

Uma empresa de
desenvolvimento de softwares
possui uma tabela com os
seguintes dados ao lado e deseja
um RELATÓRIO que você irá
ajudar a construir!



Este relatório tem o objetivo de demonstrar a importância da análise dos dados de um
projeto de desenvolvimento de software ao longo de uma semana. Os dados fornecidos
permitirão ao proprietário da equipe de desenvolvimento obter insights sobre o progresso
do projeto, identificar possíveis áreas de melhoria e tomar decisões informadas para
garantir o sucesso do projeto.
